"""
Structured Report Generator.

Converts ProtocolAnalyzer output into formatted reports for:
- PDF export (via ReportLab)
- Markdown display
- Structured JSON for API consumers
"""

import re
from datetime import datetime
from loguru import logger

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
from config import LLM_MODEL


class ReportGenerator:
    """
    Formats analysis output into structured reports.
    """

    REPORT_HEADER_TEMPLATE = """
# TrialMind Protocol Optimization Report

**Generated:** {timestamp}
**Model:** {model}
**Query Type:** {intent}
**Trials Analyzed:** {trial_count}

---
"""

    EVIDENCE_SECTION_TEMPLATE = """
## Supporting Evidence

| # | NCT ID | Type | Relevance | Indication | Phase |
|---|--------|------|-----------|------------|-------|
{evidence_rows}

*[Click NCT IDs to view on ClinicalTrials.gov]*
"""

    def generate_markdown_report(self, analysis_result: dict) -> str:
        """
        Generate a full Markdown report from ProtocolAnalyzer output.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M UTC")

        header = self.REPORT_HEADER_TEMPLATE.format(
            timestamp=timestamp,
            model=LLM_MODEL,
            intent=analysis_result.get('intent', 'unknown').replace('_', ' ').title(),
            trial_count=len(analysis_result.get('retrieved_trials', []))
        )

        # Main analysis
        analysis = analysis_result.get('analysis', '')

        # Evidence table
        evidence_table = self._build_evidence_table(
            analysis_result.get('retrieved_trials', [])
        )

        # Stats footer
        stats = analysis_result.get('retrieval_stats', {})
        footer = f"""
---
## Retrieval Statistics
- Collections queried: {', '.join(stats.get('collections_queried', []))}
- Raw candidates retrieved: {stats.get('raw_candidates', 0)}
- After deduplication: {stats.get('after_dedup', 0)}
- After reranking: {stats.get('after_rerank', 0)}
- Tokens used: {analysis_result.get('tokens_used', 0):,}

*Report generated by TrialMind RAG System*
"""

        return header + analysis + "\n\n" + evidence_table + footer

    def _build_evidence_table(self, candidates: list) -> str:
        """Build a Markdown table of retrieved evidence."""
        if not candidates:
            return "No evidence retrieved.\n"

        rows = []
        for i, candidate in enumerate(candidates[:15], 1):  # Show top 15
            meta = candidate.get('metadata', {})
            nct_id = meta.get('nct_id', 'N/A')
            chunk_type = meta.get('chunk_type', 'N/A')
            score = candidate.get('rerank_score', 0)
            conditions = meta.get('conditions_str', 'N/A')[:40]
            phase = meta.get('phase', 'N/A')

            nct_link = f"[{nct_id}](https://clinicaltrials.gov/study/{nct_id})"
            rows.append(
                f"| {i} | {nct_link} | {chunk_type} | {score:.2f} | {conditions} | {phase} |"
            )

        evidence_rows = "\n".join(rows)

        return self.EVIDENCE_SECTION_TEMPLATE.format(evidence_rows=evidence_rows)

    def generate_json_report(self, analysis_result: dict) -> dict:
        """
        Generate a structured JSON report for API consumers.
        """
        # Extract NCT citations from analysis text
        analysis_text = analysis_result.get('analysis', '')
        cited_ncts = list(set(re.findall(r'NCT\d{8}', analysis_text)))

        # Extract key sections from analysis
        sections = self._extract_sections(analysis_text)

        return {
            "report_metadata": {
                "generated_at": datetime.now().isoformat(),
                "model": LLM_MODEL,
                "query_intent": analysis_result.get('intent'),
                "trials_analyzed": len(analysis_result.get('retrieved_trials', [])),
                "tokens_used": analysis_result.get('tokens_used', 0)
            },
            "analysis": {
                "full_text": analysis_text,
                "sections": sections,
                "nct_ids_cited": cited_ncts
            },
            "evidence": [
                {
                    "nct_id": c.get('metadata', {}).get('nct_id'),
                    "chunk_type": c.get('metadata', {}).get('chunk_type'),
                    "relevance_score": c.get('rerank_score', 0),
                    "conditions": c.get('metadata', {}).get('conditions_str', ''),
                    "phase": c.get('metadata', {}).get('phase', ''),
                }
                for c in analysis_result.get('retrieved_trials', [])[:15]
            ],
            "retrieval_stats": analysis_result.get('retrieval_stats', {})
        }

    def _extract_sections(self, analysis_text: str) -> dict:
        """
        Extract numbered sections from the analysis text.
        Returns a dict mapping section_number -> section_content.
        """
        sections = {}

        # Match markdown headers (## 1. SECTION NAME)
        pattern = r'##\s+(\d+\.?\s+[A-Z][^\n]+)\n(.*?)(?=##\s+\d+|$)'
        matches = re.finditer(pattern, analysis_text, re.DOTALL)

        for match in matches:
            header = match.group(1).strip()
            content = match.group(2).strip()
            # Create clean key
            key = re.sub(r'[^\w\s]', '', header.lower())
            key = re.sub(r'\s+', '_', key.strip())
            sections[key] = content

        return sections

    def extract_key_numbers(self, analysis_text: str) -> dict:
        """
        Extract key quantitative findings from the analysis text.
        Useful for building dashboards or summary cards.
        """
        numbers = {}

        patterns = {
            'sample_size_median': r'median[^\d]*(\d+)',
            'enrollment_rate': r'(\d+(?:\.\d+)?)\s*patients?/month',
            'dropout_rate': r'dropout rate[:\s]+(\d+(?:\.\d+)?)%',
            'recruitment_challenge_pct': r'recruitment challenges?[:\s]+(\d+(?:\.\d+)?)%',
            'trial_count': r'(\d+)\s+(?:trials?|studies)',
        }

        for key, pattern in patterns.items():
            match = re.search(pattern, analysis_text.lower())
            if match:
                try:
                    numbers[key] = float(match.group(1))
                except ValueError:
                    pass

        return numbers
